// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_legendary = "CgkIyMm-4-IIEAIQDw"; // <GPGSID>
        public const string achievement_need_for_speed = "CgkIyMm-4-IIEAIQCA"; // <GPGSID>
        public const string achievement_mega_relax = "CgkIyMm-4-IIEAIQAw"; // <GPGSID>
        public const string achievement_10_pops__1_color = "CgkIyMm-4-IIEAIQCQ"; // <GPGSID>
        public const string achievement_black_hole_or_not_so_black = "CgkIyMm-4-IIEAIQBQ"; // <GPGSID>
        public const string achievement_speed_up = "CgkIyMm-4-IIEAIQBw"; // <GPGSID>
        public const string achievement_toch_the_hole = "CgkIyMm-4-IIEAIQBA"; // <GPGSID>
        public const string achievement_i_can_rule_the_time = "CgkIyMm-4-IIEAIQBg"; // <GPGSID>
        public const string achievement_blow_up_in_5_seconds = "CgkIyMm-4-IIEAIQCg"; // <GPGSID>
        public const string achievement_devil_number = "CgkIyMm-4-IIEAIQDg"; // <GPGSID>
        public const string achievement_relax = "CgkIyMm-4-IIEAIQAQ"; // <GPGSID>
        public const string achievement_super_relax = "CgkIyMm-4-IIEAIQAg"; // <GPGSID>
        public const string achievement_godlike = "CgkIyMm-4-IIEAIQEA"; // <GPGSID>
        public const string achievement_first_pops = "CgkIyMm-4-IIEAIQDA"; // <GPGSID>
        public const string achievement_300_spartanpops = "CgkIyMm-4-IIEAIQDQ"; // <GPGSID>
        public const string achievement_blow_up_in_10_seconds = "CgkIyMm-4-IIEAIQCw"; // <GPGSID>

}

